/*** Autogenerated by WIDL 10.0-rc2 from dlls/actxprxy/actxprxy_docobj.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "actxprxy_docobj.h"

#define TYPE_FORMAT_STRING_SIZE 1727
#define PROC_FORMAT_STRING_SIZE 1153

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IOleDocument interface
 */
static const unsigned short IOleDocument_FormatStringOffsetTable[] =
{
    0,  /* IOleDocument::CreateView */
    54,  /* IOleDocument::GetDocMiscStatus */
    90,  /* IOleDocument::EnumViews */
};

static const MIDL_STUBLESS_PROXY_INFO IOleDocument_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IOleDocument_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(6) _IOleDocumentProxyVtbl =
{
    {
        &IOleDocument_ProxyInfo,
        &IID_IOleDocument,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IOleDocument::CreateView */
        (void *)-1,  /* IOleDocument::GetDocMiscStatus */
        (void *)-1,  /* IOleDocument::EnumViews */
    }
};

static const MIDL_SERVER_INFO IOleDocument_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IOleDocument_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IOleDocumentStubVtbl =
{
    {
        &IID_IOleDocument,
        &IOleDocument_ServerInfo,
        6,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IOleDocumentSite interface
 */
static const unsigned short IOleDocumentSite_FormatStringOffsetTable[] =
{
    132,  /* IOleDocumentSite::ActivateMe */
};

static const MIDL_STUBLESS_PROXY_INFO IOleDocumentSite_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IOleDocumentSite_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(4) _IOleDocumentSiteProxyVtbl =
{
    {
        &IOleDocumentSite_ProxyInfo,
        &IID_IOleDocumentSite,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IOleDocumentSite::ActivateMe */
    }
};

static const MIDL_SERVER_INFO IOleDocumentSite_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IOleDocumentSite_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IOleDocumentSiteStubVtbl =
{
    {
        &IID_IOleDocumentSite,
        &IOleDocumentSite_ServerInfo,
        4,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IOleDocumentView interface
 */
static const unsigned short IOleDocumentView_FormatStringOffsetTable[] =
{
    168,  /* IOleDocumentView::SetInPlaceSite */
    204,  /* IOleDocumentView::GetInPlaceSite */
    240,  /* IOleDocumentView::GetDocument */
    276,  /* IOleDocumentView::SetRect */
    312,  /* IOleDocumentView::GetRect */
    348,  /* IOleDocumentView::SetRectComplex */
    402,  /* IOleDocumentView::Show */
    438,  /* IOleDocumentView::UIActivate */
    474,  /* IOleDocumentView::Open */
    504,  /* IOleDocumentView::CloseView */
    540,  /* IOleDocumentView::SaveViewState */
    576,  /* IOleDocumentView::ApplyViewState */
    612,  /* IOleDocumentView::Clone */
};

static const MIDL_STUBLESS_PROXY_INFO IOleDocumentView_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IOleDocumentView_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(16) _IOleDocumentViewProxyVtbl =
{
    {
        &IOleDocumentView_ProxyInfo,
        &IID_IOleDocumentView,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IOleDocumentView::SetInPlaceSite */
        (void *)-1,  /* IOleDocumentView::GetInPlaceSite */
        (void *)-1,  /* IOleDocumentView::GetDocument */
        (void *)-1,  /* IOleDocumentView::SetRect */
        (void *)-1,  /* IOleDocumentView::GetRect */
        (void *)-1,  /* IOleDocumentView::SetRectComplex */
        (void *)-1,  /* IOleDocumentView::Show */
        (void *)-1,  /* IOleDocumentView::UIActivate */
        (void *)-1,  /* IOleDocumentView::Open */
        (void *)-1,  /* IOleDocumentView::CloseView */
        (void *)-1,  /* IOleDocumentView::SaveViewState */
        (void *)-1,  /* IOleDocumentView::ApplyViewState */
        (void *)-1,  /* IOleDocumentView::Clone */
    }
};

static const MIDL_SERVER_INFO IOleDocumentView_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IOleDocumentView_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IOleDocumentViewStubVtbl =
{
    {
        &IID_IOleDocumentView,
        &IOleDocumentView_ServerInfo,
        16,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IEnumOleDocumentViews interface
 */
HRESULT STDMETHODCALLTYPE IEnumOleDocumentViews_RemoteNext_Proxy(
    IEnumOleDocumentViews* This,
    ULONG cViews,
    IOleDocumentView **rgpView,
    ULONG *pcFetched)
{
    CLIENT_CALL_RETURN _RetVal;
    struct _PARAM_STRUCT
    {
        IEnumOleDocumentViews *This;
        ULONG cViews;
        IOleDocumentView **rgpView;
        ULONG *pcFetched;
    } __params;

    __params.This = This;
    __params.cViews = cViews;
    __params.rgpView = rgpView;
    __params.pcFetched = pcFetched;
    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[654],
                              &__params );
    return (HRESULT)*(LONG_PTR *)&_RetVal;
}

void __RPC_API IEnumOleDocumentViews_RemoteNext_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        IEnumOleDocumentViews *This;
        ULONG cViews;
        IOleDocumentView **rgpView;
        ULONG *pcFetched;
        HRESULT _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = IEnumOleDocumentViews_Next_Stub( pParamStruct->This,
        pParamStruct->cViews,
        pParamStruct->rgpView,
        pParamStruct->pcFetched );
}

static const unsigned short IEnumOleDocumentViews_FormatStringOffsetTable[] =
{
    654,  /* IEnumOleDocumentViews::RemoteNext */
    702,  /* IEnumOleDocumentViews::Skip */
    738,  /* IEnumOleDocumentViews::Reset */
    768,  /* IEnumOleDocumentViews::Clone */
};

static const MIDL_STUBLESS_PROXY_INFO IEnumOleDocumentViews_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IEnumOleDocumentViews_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(7) _IEnumOleDocumentViewsProxyVtbl =
{
    {
        &IEnumOleDocumentViews_ProxyInfo,
        &IID_IEnumOleDocumentViews,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        IEnumOleDocumentViews_Next_Proxy,
        (void *)-1,  /* IEnumOleDocumentViews::Skip */
        (void *)-1,  /* IEnumOleDocumentViews::Reset */
        (void *)-1,  /* IEnumOleDocumentViews::Clone */
    }
};

static const STUB_THUNK IEnumOleDocumentViews_StubThunkTable[] =
{
    IEnumOleDocumentViews_RemoteNext_Thunk,
    0, /* IEnumOleDocumentViews::Skip */
    0, /* IEnumOleDocumentViews::Reset */
    0, /* IEnumOleDocumentViews::Clone */
};

static const MIDL_SERVER_INFO IEnumOleDocumentViews_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IEnumOleDocumentViews_FormatStringOffsetTable[-3],
    &IEnumOleDocumentViews_StubThunkTable[-3],
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IEnumOleDocumentViewsStubVtbl =
{
    {
        &IID_IEnumOleDocumentViews,
        &IEnumOleDocumentViews_ServerInfo,
        7,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IOleCommandTarget interface
 */
static const unsigned short IOleCommandTarget_FormatStringOffsetTable[] =
{
    804,  /* IOleCommandTarget::QueryStatus */
    858,  /* IOleCommandTarget::Exec */
};

static const MIDL_STUBLESS_PROXY_INFO IOleCommandTarget_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IOleCommandTarget_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IOleCommandTargetProxyVtbl =
{
    {
        &IOleCommandTarget_ProxyInfo,
        &IID_IOleCommandTarget,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IOleCommandTarget::QueryStatus */
        (void *)-1,  /* IOleCommandTarget::Exec */
    }
};

static const MIDL_SERVER_INFO IOleCommandTarget_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IOleCommandTarget_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IOleCommandTargetStubVtbl =
{
    {
        &IID_IOleCommandTarget,
        &IOleCommandTarget_ServerInfo,
        5,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IContinueCallback interface
 */
static const unsigned short IContinueCallback_FormatStringOffsetTable[] =
{
    918,  /* IContinueCallback::FContinue */
    948,  /* IContinueCallback::FContinuePrinting */
};

static const MIDL_STUBLESS_PROXY_INFO IContinueCallback_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IContinueCallback_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IContinueCallbackProxyVtbl =
{
    {
        &IContinueCallback_ProxyInfo,
        &IID_IContinueCallback,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IContinueCallback::FContinue */
        (void *)-1,  /* IContinueCallback::FContinuePrinting */
    }
};

static const MIDL_SERVER_INFO IContinueCallback_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IContinueCallback_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IContinueCallbackStubVtbl =
{
    {
        &IID_IContinueCallback,
        &IContinueCallback_ServerInfo,
        5,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IPrint interface
 */
HRESULT STDMETHODCALLTYPE IPrint_RemotePrint_Proxy(
    IPrint* This,
    DWORD grfFlags,
    DVTARGETDEVICE **pptd,
    PAGESET **pppageset,
    RemSTGMEDIUM *pstgmOptions,
    IContinueCallback *pcallback,
    LONG nFirstPage,
    LONG *pcPagesPrinted,
    LONG *pnLastPage)
{
    CLIENT_CALL_RETURN _RetVal;
    struct _PARAM_STRUCT
    {
        IPrint *This;
        DWORD grfFlags;
        DVTARGETDEVICE **pptd;
        PAGESET **pppageset;
        RemSTGMEDIUM *pstgmOptions;
        IContinueCallback *pcallback;
        LONG nFirstPage;
        LONG *pcPagesPrinted;
        LONG *pnLastPage;
    } __params;

    __params.This = This;
    __params.grfFlags = grfFlags;
    __params.pptd = pptd;
    __params.pppageset = pppageset;
    __params.pstgmOptions = pstgmOptions;
    __params.pcallback = pcallback;
    __params.nFirstPage = nFirstPage;
    __params.pcPagesPrinted = pcPagesPrinted;
    __params.pnLastPage = pnLastPage;
    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[1074],
                              &__params );
    return (HRESULT)*(LONG_PTR *)&_RetVal;
}

void __RPC_API IPrint_RemotePrint_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        IPrint *This;
        DWORD grfFlags;
        DVTARGETDEVICE **pptd;
        PAGESET **pppageset;
        RemSTGMEDIUM *pstgmOptions;
        IContinueCallback *pcallback;
        LONG nFirstPage;
        LONG *pcPagesPrinted;
        LONG *pnLastPage;
        HRESULT _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = IPrint_Print_Stub( pParamStruct->This,
        pParamStruct->grfFlags,
        pParamStruct->pptd,
        pParamStruct->pppageset,
        pParamStruct->pstgmOptions,
        pParamStruct->pcallback,
        pParamStruct->nFirstPage,
        pParamStruct->pcPagesPrinted,
        pParamStruct->pnLastPage );
}

static const unsigned short IPrint_FormatStringOffsetTable[] =
{
    996,  /* IPrint::SetInitialPageNum */
    1032,  /* IPrint::GetPageInfo */
    1074,  /* IPrint::RemotePrint */
};

static const MIDL_STUBLESS_PROXY_INFO IPrint_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IPrint_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(6) _IPrintProxyVtbl =
{
    {
        &IPrint_ProxyInfo,
        &IID_IPrint,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IPrint::SetInitialPageNum */
        (void *)-1,  /* IPrint::GetPageInfo */
        IPrint_Print_Proxy,
    }
};

static const STUB_THUNK IPrint_StubThunkTable[] =
{
    0, /* IPrint::SetInitialPageNum */
    0, /* IPrint::GetPageInfo */
    IPrint_RemotePrint_Thunk,
};

static const MIDL_SERVER_INFO IPrint_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IPrint_FormatStringOffsetTable[-3],
    &IPrint_StubThunkTable[-3],
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IPrintStubVtbl =
{
    {
        &IID_IPrint,
        &IPrint_ServerInfo,
        6,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static void __RPC_USER actxprxy_docobj_DVTARGETDEVICEExprEval_0000(PMIDL_STUB_MESSAGE pStubMsg)
{
    DVTARGETDEVICE *pS = (DVTARGETDEVICE *)(pStubMsg->StackTop - 12);
    pStubMsg->Offset = 0;
    pStubMsg->MaxCount = (ULONG_PTR)((pS->tdSize - sizeof(DWORD)) - (4 * sizeof(WORD)));
}

static const EXPR_EVAL ExprEvalRoutines[] =
{
    actxprxy_docobj_DVTARGETDEVICEExprEval_0000,
};

static const USER_MARSHAL_ROUTINE_QUADRUPLE UserMarshalRoutines[] =
{
    {
        (USER_MARSHAL_SIZING_ROUTINE)VARIANT_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)VARIANT_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)VARIANT_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)VARIANT_UserFree
    },
    {
        (USER_MARSHAL_SIZING_ROUTINE)STGMEDIUM_UserSize,
        (USER_MARSHAL_MARSHALLING_ROUTINE)STGMEDIUM_UserMarshal,
        (USER_MARSHAL_UNMARSHALLING_ROUTINE)STGMEDIUM_UserUnmarshal,
        (USER_MARSHAL_FREEING_ROUTINE)STGMEDIUM_UserFree
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, ExprEvalRoutines, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    UserMarshalRoutines,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN32__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IOleDocument::CreateView) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 24 (parameter pIPSite) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x2),	/* type offset = 2 */
/* 30 (parameter pstm) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 36 (parameter dwReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 42 (parameter ppView) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x38),	/* type offset = 56 */
/* 48 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 54 (procedure IOleDocument::GetDocMiscStatus) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 78 (parameter pdwStatus) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x09,	/* FC_ULONG */
        0x0,
/* 84 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 90 (procedure IOleDocument::EnumViews) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 114 (parameter ppEnum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x52),	/* type offset = 82 */
/* 120 (parameter ppView) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 126 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 132 (procedure IOleDocumentSite::ActivateMe) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 156 (parameter pViewToActivate) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x6c),	/* type offset = 108 */
/* 162 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 168 (procedure IOleDocumentView::SetInPlaceSite) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 192 (parameter pIPSite) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x7e),	/* type offset = 126 */
/* 198 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 204 (procedure IOleDocumentView::GetInPlaceSite) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 228 (parameter ppIPSite) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xa2),	/* type offset = 162 */
/* 234 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 240 (procedure IOleDocumentView::GetDocument) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 264 (parameter ppunk) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xb8),	/* type offset = 184 */
/* 270 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 276 (procedure IOleDocumentView::SetRect) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 300 (parameter prcView) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xbc),	/* type offset = 188 */
/* 306 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 312 (procedure IOleDocumentView::GetRect) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x1c),	/* server buffer = 28 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 336 (parameter prcView) */
        NdrFcShort(0x4112),	/* flags: must free, out, simple ref, srv size=16 */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xbc),	/* type offset = 188 */
/* 342 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 348 (procedure IOleDocumentView::SetRectComplex) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x70),	/* client buffer = 112 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x05,	/* 5 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 372 (parameter prcView) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xce),	/* type offset = 206 */
/* 378 (parameter prcHScroll) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xd2),	/* type offset = 210 */
/* 384 (parameter prcVScroll) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0xd6),	/* type offset = 214 */
/* 390 (parameter prcSizeBox) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xda),	/* type offset = 218 */
/* 396 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 402 (procedure IOleDocumentView::Show) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 426 (parameter fShow) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 432 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 438 (procedure IOleDocumentView::UIActivate) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xa),	/* method 10 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 462 (parameter fUIActivate) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 468 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 474 (procedure IOleDocumentView::Open) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xb),	/* method 11 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 498 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 504 (procedure IOleDocumentView::CloseView) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xc),	/* method 12 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 528 (parameter dwReserved) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 534 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 540 (procedure IOleDocumentView::SaveViewState) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xd),	/* method 13 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 564 (parameter pstm) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xde),	/* type offset = 222 */
/* 570 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 576 (procedure IOleDocumentView::ApplyViewState) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xe),	/* method 14 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 600 (parameter pstm) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xde),	/* type offset = 222 */
/* 606 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 612 (procedure IOleDocumentView::Clone) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0xf),	/* method 15 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x03,	/* 3 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 636 (parameter pIPSiteNew) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0xf0),	/* type offset = 240 */
/* 642 (parameter ppViewNew) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x114),	/* type offset = 276 */
/* 648 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 654 (procedure IEnumOleDocumentViews::RemoteNext) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x14),	/* stack size = 20 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x04,	/* 4 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 678 (parameter cViews) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 684 (parameter rgpView) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x12a),	/* type offset = 298 */
/* 690 (parameter pcFetched) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x09,	/* FC_ULONG */
        0x0,
/* 696 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 702 (procedure IEnumOleDocumentViews::Skip) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 726 (parameter cViews) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 732 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 738 (procedure IEnumOleDocumentViews::Reset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 762 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 768 (procedure IEnumOleDocumentViews::Clone) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 792 (parameter ppEnum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x15a),	/* type offset = 346 */
/* 798 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 804 (procedure IOleCommandTarget::QueryStatus) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x24),	/* client buffer = 36 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x05,	/* 5 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 828 (parameter pguidCmdGroup) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x170),	/* type offset = 368 */
/* 834 (parameter cCmds) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 840 (parameter prgCmds) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x17c),	/* type offset = 380 */
/* 846 (parameter pCmdText) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x1a2),	/* type offset = 418 */
/* 852 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x14),	/* stack offset = 20 */
        0x08,	/* FC_LONG */
        0x0,
/* 858 (procedure IOleCommandTarget::Exec) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x1c),	/* stack size = 28 */
        NdrFcShort(0x2c),	/* client buffer = 44 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x06,	/* 6 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 882 (parameter pguidCmdGroup) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0x4),	/* stack offset = 4 */
        NdrFcShort(0x1a6),	/* type offset = 422 */
/* 888 (parameter nCmdID) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 894 (parameter nCmdexecopt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 900 (parameter pvaIn) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x628),	/* type offset = 1576 */
/* 906 (parameter pvaOut) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x62c),	/* type offset = 1580 */
/* 912 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 918 (procedure IContinueCallback::FContinue) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x8),	/* stack size = 8 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 942 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 948 (procedure IContinueCallback::FContinuePrinting) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x14),	/* stack size = 20 */
        NdrFcShort(0x1e),	/* client buffer = 30 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x04,	/* 4 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 972 (parameter nCntPrinted) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 978 (parameter nCurPage) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 984 (parameter pwszPrintStatus) */
        NdrFcShort(0xa),	/* flags: must free, in */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x630),	/* type offset = 1584 */
/* 990 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 996 (procedure IPrint::SetInitialPageNum) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0xc),	/* stack size = 12 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1020 (parameter nFirstPage) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1026 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1032 (procedure IPrint::GetPageInfo) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x44,
        0x03,	/* 3 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1056 (parameter pnFirstPage) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1062 (parameter pcPages) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 1068 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0xc),	/* stack offset = 12 */
        0x08,	/* FC_LONG */
        0x0,
/* 1074 (procedure IPrint::RemotePrint) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x18),	/* server buffer = 24 */
        0x47,
        0x09,	/* 9 params */
        0x08,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 1098 (parameter grfFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x4),	/* stack offset = 4 */
        0x08,	/* FC_LONG */
        0x0,
/* 1104 (parameter pptd) */
        NdrFcShort(0x201b),	/* flags: must size, must free, in, out, srv size=8 */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x658),	/* type offset = 1624 */
/* 1110 (parameter pppageset) */
        NdrFcShort(0x201b),	/* flags: must size, must free, in, out, srv size=8 */
        NdrFcShort(0xc),	/* stack offset = 12 */
        NdrFcShort(0x684),	/* type offset = 1668 */
/* 1116 (parameter pstgmOptions) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x6a0),	/* type offset = 1696 */
/* 1122 (parameter pcallback) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x14),	/* stack offset = 20 */
        NdrFcShort(0x6a4),	/* type offset = 1700 */
/* 1128 (parameter nFirstPage) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 1134 (parameter pcPagesPrinted) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x1c),	/* stack offset = 28 */
        0x08,	/* FC_LONG */
        0x0,
/* 1140 (parameter pnLastPage) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 1146 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x24),	/* stack offset = 36 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (IOleInPlaceSite *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000119),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 20 (IStream *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 38 (IOleDocumentView *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc6),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 56 (IOleDocumentView **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (38) */
/* 60 (DWORD *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 64 (IEnumOleDocumentViews *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc8),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 82 (IEnumOleDocumentViews **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (64) */
/* 86 (IOleDocumentView *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc6),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 104 (IOleDocumentView **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (86) */
/* 108 (IOleDocumentView *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc6),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 126 (IOleInPlaceSite *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000119),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 144 (IOleInPlaceSite *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000119),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 162 (IOleInPlaceSite **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (144) */
/* 166 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 184 (IUnknown **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (166) */
/* 188 (struct tagRECT) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 198 (LPRECT) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff4),	/* Offset= -12 (188) */
/* 202 (LPRECT) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff0),	/* Offset= -16 (188) */
/* 206 (LPRECT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffec),	/* Offset= -20 (188) */
/* 210 (LPRECT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe8),	/* Offset= -24 (188) */
/* 214 (LPRECT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe4),	/* Offset= -28 (188) */
/* 218 (LPRECT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe0),	/* Offset= -32 (188) */
/* 222 (LPSTREAM) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000000c),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 240 (IOleInPlaceSite *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000119),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 258 (IOleDocumentView *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc6),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 276 (IOleDocumentView **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (258) */
/* 280 (IOleDocumentView *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc6),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 298 (IOleDocumentView **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x29,	/* Corr desc: parameter cViews, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x4),	/* offset = 4 */
        NdrFcShort(0x1),
        0x29,	/* Corr desc: parameter pcFetched, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0xc),	/* offset = 12 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (280) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 320 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (298) */
/* 324 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 328 (IEnumOleDocumentViews *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcc8),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 346 (IEnumOleDocumentViews **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (328) */
/* 350 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 356 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (350) */
        0x5b,	/* FC_END */
/* 368 (const GUID *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (356) */
/* 372 (OLECMD) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 380 (OLECMD[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x29,	/* Corr desc: parameter cCmds, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (372) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 396 (WCHAR[]) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x9,	/* Corr desc: field cwBuf, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x05,	/* FC_WCHAR */
        0x5b,	/* FC_END */
/* 408 (OLECMDTEXT) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0xc),	/* 12 */
        NdrFcShort(0xfff0),	/* Offset= -16 (396) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 418 (OLECMDTEXT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (408) */
/* 422 (const GUID *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffbc),	/* Offset= -68 (356) */
/* 426 (unsigned short[]) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x9,	/* Corr desc: field clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 438 (FLAGGED_WORD_BLOB) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0xfff0),	/* Offset= -16 (426) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 448 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (438) */
/* 452 (CY) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 458 (DECIMAL) */
        0x15,	/* FC_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x10),	/* 16 */
        0x06,	/* FC_SHORT */
        0x01,	/* FC_BYTE */
        0x01,	/* FC_BYTE */
        0x08,	/* FC_LONG */
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 468 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 486 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 504 (wireBSTR *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffa4),	/* Offset= -92 (438) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff9f),	/* Offset= -97 (438) */
        0x5b,	/* FC_END */
/* 538 (SAFEARR_BSTR) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (550) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 550 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd0),	/* Offset= -48 (504) */
/* 554 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 572 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (554) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 594 (SAFEARR_UNKNOWN) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (606) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 606 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (572) */
/* 610 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 628 (IDispatch **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (610) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 650 (SAFEARR_DISPATCH) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (662) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 662 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffdc),	/* Offset= -36 (628) */
/* 666 (wireVARIANT *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x352),	/* Offset= 850 (1542) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x34d),	/* Offset= 845 (1542) */
        0x5b,	/* FC_END */
/* 700 (SAFEARR_VARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (712) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 712 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd0),	/* Offset= -48 (666) */
/* 716 (IRecordInfo *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0000002f),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 734 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x4),	/* offset = 4 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 746 (struct _wireBRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (762) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffd6),	/* Offset= -42 (716) */
        0x36,	/* FC_POINTER */
        0x5b,	/* FC_END */
/* 762 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe2),	/* Offset= -30 (734) */
/* 766 (wireBRECORD *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x48, /* FC_VARIABLE_REPEAT */
        0x49, /* FC_FIXED_OFFSET */
        NdrFcShort(0x4),	/* Increment = 4 */
        NdrFcShort(0x0),	/* Offset to array = 0 */
        NdrFcShort(0x1),	/* Number of pointers = 1 */
        NdrFcShort(0x0),	/* Memory offset = 0 */
        NdrFcShort(0x0),	/* Buffer offset = 0 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffd2),	/* Offset= -46 (746) */
        0x5b,	/* FC_END */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffcd),	/* Offset= -51 (746) */
        0x5b,	/* FC_END */
/* 800 (SAFEARR_BRECORD) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        NdrFcShort(0x0),
        NdrFcShort(0x6),	/* Offset= 6 (812) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 812 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffd0),	/* Offset= -48 (766) */
/* 816 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 834 (IUnknown **) */
        0x21,	/* FC_BOGUS_ARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x0),	/* 0 */
        0x19,	/* Corr desc: field pointer Size, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        NdrFcLong(0xffffffff),	/* -1 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffdc),	/* Offset= -36 (816) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 856 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 862 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (856) */
        0x5b,	/* FC_END */
/* 874 (SAFEARR_HAVEIID) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0x0),
        NdrFcShort(0xa),	/* Offset= 10 (890) */
        0x08,	/* FC_LONG */
        0x36,	/* FC_POINTER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (862) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 890 */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc6),	/* Offset= -58 (834) */
/* 894 (byte *) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 906 (BYTE_SIZEDARR) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (894) */
        0x5b,	/* FC_END */
        0x08,	/* FC_LONG */
        0x8,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 926 (unsigned short *) */
        0x1b,	/* FC_CARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x2),	/* 2 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 938 (WORD_SIZEDARR) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (926) */
        0x5b,	/* FC_END */
        0x08,	/* FC_LONG */
        0x8,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 958 (ULONG *) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x4),	/* 4 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 970 (DWORD_SIZEDARR) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (958) */
        0x5b,	/* FC_END */
        0x08,	/* FC_LONG */
        0x8,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 990 (hyper *) */
        0x1b,	/* FC_CARRAY */
        0x7,	/* 7 */
        NdrFcShort(0x8),	/* 8 */
        0x19,	/* Corr desc: field pointer clSize, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x0),	/* offset = 0 */
        NdrFcShort(0x1),
        0x0b,	/* FC_HYPER */
        0x5b,	/* FC_END */
/* 1002 (HYPER_SIZEDARR) */
        0x16,	/* FC_PSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x4b,	/* FC_PP */
        0x5c,	/* FC_PAD */
        0x46, /* FC_NO_REPEAT */
        0x5c, /* FC_PAD */
        NdrFcShort(0x4),	/* Memory offset = 4 */
        NdrFcShort(0x4),	/* Buffer offset = 4 */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffe6),	/* Offset= -26 (990) */
        0x5b,	/* FC_END */
        0x08,	/* FC_LONG */
        0x8,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1022 (SAFEARRAYUNION) */
        0x2a,	/* FC_ENCAPSULATED_UNION */
        0x49,	/* Switch type= FC_ULONG */
        NdrFcShort(0x18),	/* 24 */
        NdrFcShort(0xa),	/* 10 */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xfe12),	/* Offset= -494 (538) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfe44),	/* Offset= -444 (594) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfe76),	/* Offset= -394 (650) */
        NdrFcLong(0xc),	/* 12 */
        NdrFcShort(0xfea2),	/* Offset= -350 (700) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xff00),	/* Offset= -256 (800) */
        NdrFcLong(0x800d),	/* 32781 */
        NdrFcShort(0xff44),	/* Offset= -188 (874) */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0xff5e),	/* Offset= -162 (906) */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0xff78),	/* Offset= -136 (938) */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0xff92),	/* Offset= -110 (970) */
        NdrFcLong(0x14),	/* 20 */
        NdrFcShort(0xffac),	/* Offset= -84 (1002) */
        NdrFcShort(0xffff),
/* 1090 (SAFEARRAYBOUND) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1098 (SAFEARRAYBOUND[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x7,	/* Corr desc: field cDims, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xffd8),	/* offset = -40 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (1090) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1114 (struct _wireSAFEARRAY) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x28),	/* 40 */
        NdrFcShort(0xffec),	/* Offset= -20 (1098) */
        NdrFcShort(0x0),	/* Offset= 0 (1120) */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff96),	/* Offset= -106 (1022) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1132 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffec),	/* Offset= -20 (1114) */
/* 1136 (signed char *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x02,	/* FC_CHAR */
        0x5c,	/* FC_PAD */
/* 1140 (USHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x07,	/* FC_USHORT */
        0x5c,	/* FC_PAD */
/* 1144 (ULONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1148 (INT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1152 (UINT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 1156 (BYTE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x01,	/* FC_BYTE */
        0x5c,	/* FC_PAD */
/* 1160 (SHORT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 1164 (LONG *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1168 (FLOAT *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0a,	/* FC_FLOAT */
        0x5c,	/* FC_PAD */
/* 1172 (DOUBLE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 1176 (VARIANT_BOOL *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x06,	/* FC_SHORT */
        0x5c,	/* FC_PAD */
/* 1180 (SCODE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1184 (DATE *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x0c,	/* FC_DOUBLE */
        0x5c,	/* FC_PAD */
/* 1188 (wireBSTR) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd10),	/* Offset= -752 (438) */
/* 1192 (wireBSTR *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1188) */
/* 1196 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0x158),	/* Offset= 344 (1542) */
/* 1200 (wireVARIANT *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1196) */
/* 1204 (CY *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd0e),	/* Offset= -754 (452) */
/* 1208 (DECIMAL *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfd10),	/* Offset= -752 (458) */
/* 1212 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 1230 (IUnknown **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (1212) */
/* 1234 (IDispatch *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00020400),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 1252 (IDispatch **) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (1234) */
/* 1256 (wireSAFEARRAY) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xff70),	/* Offset= -144 (1114) */
/* 1260 (wireSAFEARRAY *) */
        0x12, 0x10,		/* FC_UP [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1256) */
/* 1264 (wireBRECORD) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfdf8),	/* Offset= -520 (746) */
/* 1268 (union ) */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x2b),	/* 43 */
        NdrFcLong(0x0),	/* 0 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x1),	/* 1 */
        NdrFcShort(0x0),	/* No type */
        NdrFcLong(0x10),	/* 16 */
        NdrFcShort(0x8002),	/* Simple arm type: FC_CHAR */
        NdrFcLong(0x12),	/* 18 */
        NdrFcShort(0x8007),	/* Simple arm type: FC_USHORT */
        NdrFcLong(0x13),	/* 19 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x16),	/* 22 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x17),	/* 23 */
        NdrFcShort(0x8009),	/* Simple arm type: FC_ULONG */
        NdrFcLong(0x11),	/* 17 */
        NdrFcShort(0x8001),	/* Simple arm type: FC_BYTE */
        NdrFcLong(0x2),	/* 2 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0x3),	/* 3 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x4),	/* 4 */
        NdrFcShort(0x800a),	/* Simple arm type: FC_FLOAT */
        NdrFcLong(0x5),	/* 5 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0xb),	/* 11 */
        NdrFcShort(0x8006),	/* Simple arm type: FC_SHORT */
        NdrFcLong(0xa),	/* 10 */
        NdrFcShort(0x8008),	/* Simple arm type: FC_LONG */
        NdrFcLong(0x7),	/* 7 */
        NdrFcShort(0x800c),	/* Simple arm type: FC_DOUBLE */
        NdrFcLong(0x8),	/* 8 */
        NdrFcShort(0xff4e),	/* Offset= -178 (1188) */
        NdrFcLong(0x6),	/* 6 */
        NdrFcShort(0xfc68),	/* Offset= -920 (452) */
        NdrFcLong(0xe),	/* 14 */
        NdrFcShort(0xfc68),	/* Offset= -920 (458) */
        NdrFcLong(0xd),	/* 13 */
        NdrFcShort(0xfc6c),	/* Offset= -916 (468) */
        NdrFcLong(0x9),	/* 9 */
        NdrFcShort(0xfc78),	/* Offset= -904 (486) */
        NdrFcLong(0x2000),	/* 8192 */
        NdrFcShort(0xff74),	/* Offset= -140 (1256) */
        NdrFcLong(0x4010),	/* 16400 */
        NdrFcShort(0xfef6),	/* Offset= -266 (1136) */
        NdrFcLong(0x4012),	/* 16402 */
        NdrFcShort(0xfef4),	/* Offset= -268 (1140) */
        NdrFcLong(0x4013),	/* 16403 */
        NdrFcShort(0xfef2),	/* Offset= -270 (1144) */
        NdrFcLong(0x4016),	/* 16406 */
        NdrFcShort(0xfef0),	/* Offset= -272 (1148) */
        NdrFcLong(0x4017),	/* 16407 */
        NdrFcShort(0xfeee),	/* Offset= -274 (1152) */
        NdrFcLong(0x4011),	/* 16401 */
        NdrFcShort(0xfeec),	/* Offset= -276 (1156) */
        NdrFcLong(0x4002),	/* 16386 */
        NdrFcShort(0xfeea),	/* Offset= -278 (1160) */
        NdrFcLong(0x4003),	/* 16387 */
        NdrFcShort(0xfee8),	/* Offset= -280 (1164) */
        NdrFcLong(0x4004),	/* 16388 */
        NdrFcShort(0xfee6),	/* Offset= -282 (1168) */
        NdrFcLong(0x4005),	/* 16389 */
        NdrFcShort(0xfee4),	/* Offset= -284 (1172) */
        NdrFcLong(0x400b),	/* 16395 */
        NdrFcShort(0xfee2),	/* Offset= -286 (1176) */
        NdrFcLong(0x400a),	/* 16394 */
        NdrFcShort(0xfee0),	/* Offset= -288 (1180) */
        NdrFcLong(0x4007),	/* 16391 */
        NdrFcShort(0xfede),	/* Offset= -290 (1184) */
        NdrFcLong(0x4008),	/* 16392 */
        NdrFcShort(0xfee0),	/* Offset= -288 (1192) */
        NdrFcLong(0x400c),	/* 16396 */
        NdrFcShort(0xfee2),	/* Offset= -286 (1200) */
        NdrFcLong(0x4006),	/* 16390 */
        NdrFcShort(0xfee0),	/* Offset= -288 (1204) */
        NdrFcLong(0x400e),	/* 16398 */
        NdrFcShort(0xfede),	/* Offset= -290 (1208) */
        NdrFcLong(0x400d),	/* 16397 */
        NdrFcShort(0xfeee),	/* Offset= -274 (1230) */
        NdrFcLong(0x4009),	/* 16393 */
        NdrFcShort(0xfefe),	/* Offset= -258 (1252) */
        NdrFcLong(0x6000),	/* 24576 */
        NdrFcShort(0xff00),	/* Offset= -256 (1260) */
        NdrFcLong(0x24),	/* 36 */
        NdrFcShort(0xfefe),	/* Offset= -258 (1264) */
        NdrFcLong(0x4024),	/* 16420 */
        NdrFcShort(0xfef8),	/* Offset= -264 (1264) */
        NdrFcShort(0xffff),
/* 1532 */
        0x2b,	/* FC_NON_ENCAPSULATED_UNION */
        0x7,	/* FC_USHORT */
        0x7,	/* Corr desc: field vt, FC_USHORT */
        0x0,	/* no operators */
        NdrFcShort(0xfff8),	/* offset = -8 */
        NdrFcShort(0x1),
        NdrFcShort(0xfef0),	/* Offset= -272 (1268) */
/* 1542 (struct _wireVARIANT) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x7,	/* 7 */
        NdrFcShort(0x20),	/* 32 */
        NdrFcShort(0x0),
        NdrFcShort(0x0),	/* Offset= 0 (1548) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (1532) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1562 (wireVARIANT) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffea),	/* Offset= -22 (1542) */
/* 1566 (VARIANT) */
        0xb4,	/* FC_USER_MARSHAL */
        0x83,	/* Alignment= 3, Flags= 80 */
        NdrFcShort(0x0),	/* Function offset= 0 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0xfff4),	/* Offset= -12 (1562) */
/* 1576 (VARIANT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff4),	/* Offset= -12 (1566) */
/* 1580 (VARIANT *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff0),	/* Offset= -16 (1566) */
/* 1584 (WCHAR *) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
        0x05,	/* FC_WCHAR */
        0x5c,	/* FC_PAD */
/* 1588 (LONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1592 (LONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1596 (BYTE[]) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x0,	/* Corr desc: field in DVTARGETDEVICE */
        0x59,	/* FC_CALLBACK */
        NdrFcShort(0x0),	/* 0 */
        NdrFcShort(0x0),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1608 (DVTARGETDEVICE) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0xc),	/* 12 */
        NdrFcShort(0xfff0),	/* Offset= -16 (1596) */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x5b,	/* FC_END */
/* 1620 (DVTARGETDEVICE *) */
        0x13, 0x0,		/* FC_OP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1608) */
/* 1624 (DVTARGETDEVICE **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1620) */
/* 1628 (PAGERANGE) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1636 (PAGERANGE[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x9,	/* Corr desc: field cPageRange, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffec),	/* Offset= -20 (1628) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1652 (PAGESET) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        NdrFcShort(0xffec),	/* Offset= -20 (1636) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 1664 (PAGESET *) */
        0x13, 0x0,		/* FC_OP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1652) */
/* 1668 (PAGESET **) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (1664) */
/* 1672 (byte[]) */
        0x1b,	/* FC_CARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x1),	/* 1 */
        0x9,	/* Corr desc: field cbData, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0xfffc),	/* offset = -4 */
        NdrFcShort(0x1),
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 1684 (RemSTGMEDIUM) */
        0x17,	/* FC_CSTRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x14),	/* 20 */
        NdrFcShort(0xfff0),	/* Offset= -16 (1672) */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5b,	/* FC_END */
/* 1696 (RemSTGMEDIUM *) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xfff2),	/* Offset= -14 (1684) */
/* 1700 (IContinueCallback *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bcca),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 1718 (LONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
/* 1722 (LONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _actxprxy_docobj_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IOleDocumentProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IOleDocumentViewProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IOleDocumentSiteProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IEnumOleDocumentViewsProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IPrintProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IContinueCallbackProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IOleCommandTargetProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _actxprxy_docobj_StubVtblList[] =
{
    &_IOleDocumentStubVtbl,
    &_IOleDocumentViewStubVtbl,
    &_IOleDocumentSiteStubVtbl,
    &_IEnumOleDocumentViewsStubVtbl,
    &_IPrintStubVtbl,
    &_IContinueCallbackStubVtbl,
    &_IOleCommandTargetStubVtbl,
    0
};

static PCInterfaceName const _actxprxy_docobj_InterfaceNamesList[] =
{
    "IOleDocument",
    "IOleDocumentView",
    "IOleDocumentSite",
    "IEnumOleDocumentViews",
    "IPrint",
    "IContinueCallback",
    "IOleCommandTarget",
    0
};

static int __stdcall _actxprxy_docobj_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 6;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_actxprxy_docobj, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo actxprxy_docobj_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_actxprxy_docobj_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_actxprxy_docobj_StubVtblList,
    _actxprxy_docobj_InterfaceNamesList,
    0,
    _actxprxy_docobj_IID_Lookup,
    7,
    2,
    0,
    0,
    0,
    0
};
