/*** Autogenerated by WIDL 10.0-rc2 from dlls/actxprxy/actxprxy_comcat.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "actxprxy_comcat.h"

#define TYPE_FORMAT_STRING_SIZE 485
#define PROC_FORMAT_STRING_SIZE 911

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IEnumGUID interface
 */
static const unsigned short IEnumGUID_FormatStringOffsetTable[] =
{
    0,  /* IEnumGUID::Next */
    50,  /* IEnumGUID::Skip */
    88,  /* IEnumGUID::Reset */
    120,  /* IEnumGUID::Clone */
};

static const MIDL_STUBLESS_PROXY_INFO IEnumGUID_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IEnumGUID_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(7) _IEnumGUIDProxyVtbl =
{
    {
        &IEnumGUID_ProxyInfo,
        &IID_IEnumGUID,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IEnumGUID::Next */
        (void *)-1,  /* IEnumGUID::Skip */
        (void *)-1,  /* IEnumGUID::Reset */
        (void *)-1,  /* IEnumGUID::Clone */
    }
};

static const MIDL_SERVER_INFO IEnumGUID_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IEnumGUID_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IEnumGUIDStubVtbl =
{
    {
        &IID_IEnumGUID,
        &IEnumGUID_ServerInfo,
        7,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IEnumCATEGORYINFO interface
 */
static const unsigned short IEnumCATEGORYINFO_FormatStringOffsetTable[] =
{
    158,  /* IEnumCATEGORYINFO::Next */
    208,  /* IEnumCATEGORYINFO::Skip */
    246,  /* IEnumCATEGORYINFO::Reset */
    278,  /* IEnumCATEGORYINFO::Clone */
};

static const MIDL_STUBLESS_PROXY_INFO IEnumCATEGORYINFO_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IEnumCATEGORYINFO_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(7) _IEnumCATEGORYINFOProxyVtbl =
{
    {
        &IEnumCATEGORYINFO_ProxyInfo,
        &IID_IEnumCATEGORYINFO,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IEnumCATEGORYINFO::Next */
        (void *)-1,  /* IEnumCATEGORYINFO::Skip */
        (void *)-1,  /* IEnumCATEGORYINFO::Reset */
        (void *)-1,  /* IEnumCATEGORYINFO::Clone */
    }
};

static const MIDL_SERVER_INFO IEnumCATEGORYINFO_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IEnumCATEGORYINFO_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IEnumCATEGORYINFOStubVtbl =
{
    {
        &IID_IEnumCATEGORYINFO,
        &IEnumCATEGORYINFO_ServerInfo,
        7,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * ICatInformation interface
 */
HRESULT STDMETHODCALLTYPE ICatInformation_RemoteEnumClassesOfCategories_Proxy(
    ICatInformation* This,
    ULONG cImplemented,
    CATID rgcatidImpl[],
    ULONG cRequired,
    CATID rgcatidReq[],
    IEnumGUID **ppenumClsid)
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[410],
                              This,
                              cImplemented,
                              rgcatidImpl,
                              cRequired,
                              rgcatidReq,
                              ppenumClsid );
    return (HRESULT)_RetVal.Simple;
}

void __RPC_API ICatInformation_RemoteEnumClassesOfCategories_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        ICatInformation *This;
        ULONG DECLSPEC_ALIGN(8) cImplemented;
        CATID *rgcatidImpl;
        ULONG DECLSPEC_ALIGN(8) cRequired;
        CATID *rgcatidReq;
        IEnumGUID **ppenumClsid;
        HRESULT DECLSPEC_ALIGN(8) _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = ICatInformation_EnumClassesOfCategories_Stub( pParamStruct->This,
        pParamStruct->cImplemented,
        pParamStruct->rgcatidImpl,
        pParamStruct->cRequired,
        pParamStruct->rgcatidReq,
        pParamStruct->ppenumClsid );
}

HRESULT STDMETHODCALLTYPE ICatInformation_RemoteIsClassOfCategories_Proxy(
    ICatInformation* This,
    REFCLSID rclsid,
    ULONG cImplemented,
    CATID rgcatidImpl[],
    ULONG cRequired,
    CATID rgcatidReq[])
{
    CLIENT_CALL_RETURN _RetVal;

    _RetVal = NdrClientCall2( &Object_StubDesc,
                              &__MIDL_ProcFormatString.Format[472],
                              This,
                              rclsid,
                              cImplemented,
                              rgcatidImpl,
                              cRequired,
                              rgcatidReq );
    return (HRESULT)_RetVal.Simple;
}

void __RPC_API ICatInformation_RemoteIsClassOfCategories_Thunk( PMIDL_STUB_MESSAGE pStubMsg )
{
    struct _PARAM_STRUCT
    {
        ICatInformation *This;
        REFCLSID rclsid;
        ULONG DECLSPEC_ALIGN(8) cImplemented;
        CATID *rgcatidImpl;
        ULONG DECLSPEC_ALIGN(8) cRequired;
        CATID *rgcatidReq;
        HRESULT DECLSPEC_ALIGN(8) _RetVal;
    } *pParamStruct = (struct _PARAM_STRUCT *)pStubMsg->StackTop;

    pParamStruct->_RetVal = ICatInformation_IsClassOfCategories_Stub( pParamStruct->This,
        pParamStruct->rclsid,
        pParamStruct->cImplemented,
        pParamStruct->rgcatidImpl,
        pParamStruct->cRequired,
        pParamStruct->rgcatidReq );
}

static const unsigned short ICatInformation_FormatStringOffsetTable[] =
{
    316,  /* ICatInformation::EnumCategories */
    360,  /* ICatInformation::GetCategoryDesc */
    410,  /* ICatInformation::RemoteEnumClassesOfCategories */
    472,  /* ICatInformation::RemoteIsClassOfCategories */
    534,  /* ICatInformation::EnumImplCategoriesOfClass */
    578,  /* ICatInformation::EnumReqCategoriesOfClass */
};

static const MIDL_STUBLESS_PROXY_INFO ICatInformation_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &ICatInformation_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(9) _ICatInformationProxyVtbl =
{
    {
        &ICatInformation_ProxyInfo,
        &IID_ICatInformation,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* ICatInformation::EnumCategories */
        (void *)-1,  /* ICatInformation::GetCategoryDesc */
        ICatInformation_EnumClassesOfCategories_Proxy,
        ICatInformation_IsClassOfCategories_Proxy,
        (void *)-1,  /* ICatInformation::EnumImplCategoriesOfClass */
        (void *)-1,  /* ICatInformation::EnumReqCategoriesOfClass */
    }
};

static const STUB_THUNK ICatInformation_StubThunkTable[] =
{
    0, /* ICatInformation::EnumCategories */
    0, /* ICatInformation::GetCategoryDesc */
    ICatInformation_RemoteEnumClassesOfCategories_Thunk,
    ICatInformation_RemoteIsClassOfCategories_Thunk,
    0, /* ICatInformation::EnumImplCategoriesOfClass */
    0, /* ICatInformation::EnumReqCategoriesOfClass */
};

static const MIDL_SERVER_INFO ICatInformation_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &ICatInformation_FormatStringOffsetTable[-3],
    &ICatInformation_StubThunkTable[-3],
    0,
    0,
    0
};

static const CInterfaceStubVtbl _ICatInformationStubVtbl =
{
    {
        &IID_ICatInformation,
        &ICatInformation_ServerInfo,
        9,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * ICatRegister interface
 */
static const unsigned short ICatRegister_FormatStringOffsetTable[] =
{
    622,  /* ICatRegister::RegisterCategories */
    666,  /* ICatRegister::UnRegisterCategories */
    710,  /* ICatRegister::RegisterClassImplCategories */
    760,  /* ICatRegister::UnRegisterClassImplCategories */
    810,  /* ICatRegister::RegisterClassReqCategories */
    860,  /* ICatRegister::UnRegisterClassReqCategories */
};

static const MIDL_STUBLESS_PROXY_INFO ICatRegister_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &ICatRegister_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(9) _ICatRegisterProxyVtbl =
{
    {
        &ICatRegister_ProxyInfo,
        &IID_ICatRegister,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* ICatRegister::RegisterCategories */
        (void *)-1,  /* ICatRegister::UnRegisterCategories */
        (void *)-1,  /* ICatRegister::RegisterClassImplCategories */
        (void *)-1,  /* ICatRegister::UnRegisterClassImplCategories */
        (void *)-1,  /* ICatRegister::RegisterClassReqCategories */
        (void *)-1,  /* ICatRegister::UnRegisterClassReqCategories */
    }
};

static const MIDL_SERVER_INFO ICatRegister_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &ICatRegister_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _ICatRegisterStubVtbl =
{
    {
        &IID_ICatRegister,
        &ICatRegister_ServerInfo,
        9,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IEnumGUID::Next) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 32 (parameter rgelt) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x14),	/* type offset = 20 */
/* 38 (parameter pceltFetched) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 44 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 50 (procedure IEnumGUID::Skip) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 76 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 88 (procedure IEnumGUID::Reset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 114 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 120 (procedure IEnumGUID::Clone) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 146 (parameter ppenum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x44),	/* type offset = 68 */
/* 152 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 158 (procedure IEnumCATEGORYINFO::Next) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 184 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 190 (parameter rgelt) */
        NdrFcShort(0x113),	/* flags: must size, must free, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x6e),	/* type offset = 110 */
/* 196 (parameter pceltFetched) */
        NdrFcShort(0x2150),	/* flags: out, base type, simple ref, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 202 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 208 (procedure IEnumCATEGORYINFO::Skip) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 234 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 240 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 246 (procedure IEnumCATEGORYINFO::Reset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 272 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 278 (procedure IEnumCATEGORYINFO::Clone) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 304 (parameter ppenum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x9e),	/* type offset = 158 */
/* 310 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 316 (procedure ICatInformation::EnumCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 342 (parameter lcid) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 348 (parameter ppenumCategoryInfo) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xb4),	/* type offset = 180 */
/* 354 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 360 (procedure ICatInformation::GetCategoryDesc) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 386 (parameter rcatid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x8),	/* type offset = 8 */
/* 392 (parameter lcid) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 398 (parameter pszDesc) */
        NdrFcShort(0x2013),	/* flags: must size, must free, out, srv size=8 */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0xc0),	/* type offset = 192 */
/* 404 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 410 (procedure ICatInformation::RemoteEnumClassesOfCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 436 (parameter cImplemented) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 442 (parameter rgcatidImpl) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xd4),	/* type offset = 212 */
/* 448 (parameter cRequired) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 454 (parameter rgcatidReq) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x20),	/* stack offset = 32 */
        NdrFcShort(0xe8),	/* type offset = 232 */
/* 460 (parameter ppenumClsid) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xfe),	/* type offset = 254 */
/* 466 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 472 (procedure ICatInformation::RemoteIsClassOfCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x38),	/* stack size = 56 */
        NdrFcShort(0x24),	/* client buffer = 36 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x06,	/* 6 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 498 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 504 (parameter cImplemented) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 510 (parameter rgcatidImpl) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x128),	/* type offset = 296 */
/* 516 (parameter cRequired) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 522 (parameter rgcatidReq) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0x13c),	/* type offset = 316 */
/* 528 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x30),	/* stack offset = 48 */
        0x08,	/* FC_LONG */
        0x0,
/* 534 (procedure ICatInformation::EnumImplCategoriesOfClass) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 560 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 566 (parameter ppenumCatid) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x156),	/* type offset = 342 */
/* 572 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 578 (procedure ICatInformation::EnumReqCategoriesOfClass) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 604 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 610 (parameter ppenumCatid) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x170),	/* type offset = 368 */
/* 616 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 622 (procedure ICatRegister::RegisterCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 648 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 654 (parameter rgCategoryInfo) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x174),	/* type offset = 372 */
/* 660 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 666 (procedure ICatRegister::UnRegisterCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 692 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 698 (parameter rgcatid) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x184),	/* type offset = 388 */
/* 704 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 710 (procedure ICatRegister::RegisterClassImplCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 736 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 742 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 748 (parameter rgcatid) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x198),	/* type offset = 408 */
/* 754 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 760 (procedure ICatRegister::UnRegisterClassImplCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 786 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 792 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 798 (parameter rgcatid) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x1ac),	/* type offset = 428 */
/* 804 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 810 (procedure ICatRegister::RegisterClassReqCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 836 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 842 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 848 (parameter rgcatid) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x1c0),	/* type offset = 448 */
/* 854 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 860 (procedure ICatRegister::UnRegisterClassReqCategories) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x1c),	/* client buffer = 28 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 886 (parameter rclsid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x108),	/* type offset = 264 */
/* 892 (parameter cCategories) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 898 (parameter rgcatid) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x1d4),	/* type offset = 468 */
/* 904 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 8 (GUID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (2) */
        0x5b,	/* FC_END */
/* 20 (GUID *) */
        0x1c,	/* FC_CVARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter celt, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x29,	/* Corr desc: parameter pceltFetched, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (8) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 42 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (20) */
/* 46 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 50 (IEnumGUID *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 68 (IEnumGUID **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (50) */
/* 72 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 78 (CATID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (72) */
        0x5b,	/* FC_END */
/* 90 (OLECHAR[128]) */
        0x1d,	/* FC_SMFARRAY */
        0x1,	/* 1 */
        NdrFcShort(0x100),	/* 256 */
        0x05,	/* FC_WCHAR */
        0x5b,	/* FC_END */
/* 96 (CATEGORYINFO) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x114),	/* 276 */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe8),	/* Offset= -24 (78) */
        0x08,	/* FC_LONG */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffef),	/* Offset= -17 (90) */
        0x5b,	/* FC_END */
/* 110 (CATEGORYINFO *) */
        0x1c,	/* FC_CVARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x114),	/* 276 */
        0x29,	/* Corr desc: parameter celt, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x29,	/* Corr desc: parameter pceltFetched, FC_ULONG */
        0x54,	/* FC_DEREFERENCE */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x0),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe0),	/* Offset= -32 (96) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 132 */
        0x11, 0x0,	/* FC_RP */
        NdrFcShort(0xffe8),	/* Offset= -24 (110) */
/* 136 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 140 (IEnumCATEGORYINFO *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e011),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 158 (IEnumCATEGORYINFO **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (140) */
/* 162 (IEnumCATEGORYINFO *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e011),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 180 (IEnumCATEGORYINFO **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (162) */
/* 184 (REFCATID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff4e),	/* Offset= -178 (8) */
/* 188 (LPWSTR) */
        0x13, 0x8,	/* FC_OP [simple_pointer] */
/* 190 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 192 (LPWSTR *) */
        0x11, 0x14,		/* FC_RP [allocated_on_stack] [pointer_deref] */
        NdrFcShort(0xfffa),	/* Offset= -6 (188) */
/* 196 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cImplemented, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff7e),	/* Offset= -130 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 212 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (196) */
/* 216 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cRequired, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x18),	/* offset = 24 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff6a),	/* Offset= -150 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 232 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (216) */
/* 236 (IEnumGUID *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 254 (IEnumGUID **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (236) */
/* 258 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 264 (CLSID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (258) */
        0x5b,	/* FC_END */
/* 276 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (264) */
/* 280 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cImplemented, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff2a),	/* Offset= -214 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 296 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (280) */
/* 300 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cRequired, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x20),	/* offset = 32 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xff16),	/* Offset= -234 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 316 */
        0x12, 0x0,	/* FC_UP */
        NdrFcShort(0xffee),	/* Offset= -18 (300) */
/* 320 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffc6),	/* Offset= -58 (264) */
/* 324 (IEnumGUID *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 342 (IEnumGUID **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (324) */
/* 346 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffac),	/* Offset= -84 (264) */
/* 350 (IEnumGUID *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x0002e000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

/* 368 (IEnumGUID **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (350) */
/* 372 (CATEGORYINFO[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x114),	/* 276 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfee0),	/* Offset= -288 (96) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 388 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x8),	/* offset = 8 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfebe),	/* Offset= -322 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 404 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff72),	/* Offset= -142 (264) */
/* 408 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfeaa),	/* Offset= -342 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 424 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff5e),	/* Offset= -162 (264) */
/* 428 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfe96),	/* Offset= -362 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 444 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff4a),	/* Offset= -182 (264) */
/* 448 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfe82),	/* Offset= -382 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 464 (REFCLSID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xff36),	/* Offset= -202 (264) */
/* 468 (CATID[]) */
        0x1b,	/* FC_CARRAY */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x29,	/* Corr desc: parameter cCategories, FC_ULONG */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x1),
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfe6e),	/* Offset= -402 (78) */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
        0x0
    }
};

static const CInterfaceProxyVtbl* const _actxprxy_comcat_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IEnumGUIDProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IEnumCATEGORYINFOProxyVtbl,
    (const CInterfaceProxyVtbl*)&_ICatRegisterProxyVtbl,
    (const CInterfaceProxyVtbl*)&_ICatInformationProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _actxprxy_comcat_StubVtblList[] =
{
    &_IEnumGUIDStubVtbl,
    &_IEnumCATEGORYINFOStubVtbl,
    &_ICatRegisterStubVtbl,
    &_ICatInformationStubVtbl,
    0
};

static PCInterfaceName const _actxprxy_comcat_InterfaceNamesList[] =
{
    "IEnumGUID",
    "IEnumCATEGORYINFO",
    "ICatRegister",
    "ICatInformation",
    0
};

static int __stdcall _actxprxy_comcat_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 3;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_actxprxy_comcat, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo actxprxy_comcat_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_actxprxy_comcat_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_actxprxy_comcat_StubVtblList,
    _actxprxy_comcat_InterfaceNamesList,
    0,
    _actxprxy_comcat_IID_Lookup,
    4,
    2,
    0,
    0,
    0,
    0
};
