/*** Autogenerated by WIDL 10.0-rc2 from dlls/actxprxy/actxprxy_urlhist.idl - Do not edit ***/

#define __midl_proxy
#include "objbase.h"

#ifndef __REDQ_RPCPROXY_H_VERSION__
#define __REQUIRED_RPCPROXY_H_VERSION__ 475
#endif

#define USE_STUBLESS_PROXY
#include "rpcproxy.h"
#ifndef __RPCPROXY_H_VERSION__
#error This code needs a newer version of rpcproxy.h
#endif /* __RPCPROXY_H_VERSION__ */

#include "actxprxy_urlhist.h"

#define TYPE_FORMAT_STRING_SIZE 213
#define PROC_FORMAT_STRING_SIZE 535

typedef struct _MIDL_TYPE_FORMAT_STRING
{
    short Pad;
    unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING
{
    short Pad;
    unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;


static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

static const MIDL_STUB_DESC Object_StubDesc;

/*****************************************************************************
 * IEnumSTATURL interface
 */
static const unsigned short IEnumSTATURL_FormatStringOffsetTable[] =
{
    0,  /* IEnumSTATURL::Next */
    50,  /* IEnumSTATURL::Skip */
    88,  /* IEnumSTATURL::Reset */
    120,  /* IEnumSTATURL::Clone */
    158,  /* IEnumSTATURL::SetFilter */
};

static const MIDL_STUBLESS_PROXY_INFO IEnumSTATURL_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IEnumSTATURL_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(8) _IEnumSTATURLProxyVtbl =
{
    {
        &IEnumSTATURL_ProxyInfo,
        &IID_IEnumSTATURL,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IEnumSTATURL::Next */
        (void *)-1,  /* IEnumSTATURL::Skip */
        (void *)-1,  /* IEnumSTATURL::Reset */
        (void *)-1,  /* IEnumSTATURL::Clone */
        (void *)-1,  /* IEnumSTATURL::SetFilter */
    }
};

static const MIDL_SERVER_INFO IEnumSTATURL_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IEnumSTATURL_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IEnumSTATURLStubVtbl =
{
    {
        &IID_IEnumSTATURL,
        &IEnumSTATURL_ServerInfo,
        8,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IUrlHistoryStg interface
 */
static const unsigned short IUrlHistoryStg_FormatStringOffsetTable[] =
{
    202,  /* IUrlHistoryStg::AddUrl */
    252,  /* IUrlHistoryStg::DeleteUrl */
    296,  /* IUrlHistoryStg::QueryUrl */
    346,  /* IUrlHistoryStg::BindToObject */
    396,  /* IUrlHistoryStg::EnumUrls */
};

static const MIDL_STUBLESS_PROXY_INFO IUrlHistoryStg_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryStg_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(8) _IUrlHistoryStgProxyVtbl =
{
    {
        &IUrlHistoryStg_ProxyInfo,
        &IID_IUrlHistoryStg,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IUrlHistoryStg::AddUrl */
        (void *)-1,  /* IUrlHistoryStg::DeleteUrl */
        (void *)-1,  /* IUrlHistoryStg::QueryUrl */
        (void *)-1,  /* IUrlHistoryStg::BindToObject */
        (void *)-1,  /* IUrlHistoryStg::EnumUrls */
    }
};

static const MIDL_SERVER_INFO IUrlHistoryStg_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryStg_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IUrlHistoryStgStubVtbl =
{
    {
        &IID_IUrlHistoryStg,
        &IUrlHistoryStg_ServerInfo,
        8,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

/*****************************************************************************
 * IUrlHistoryStg2 interface
 */
static const unsigned short IUrlHistoryStg2_FormatStringOffsetTable[] =
{
    202,  /* IUrlHistoryStg::AddUrl */
    252,  /* IUrlHistoryStg::DeleteUrl */
    296,  /* IUrlHistoryStg::QueryUrl */
    346,  /* IUrlHistoryStg::BindToObject */
    396,  /* IUrlHistoryStg::EnumUrls */
    434,  /* IUrlHistoryStg2::AddUrlAndNotify */
    502,  /* IUrlHistoryStg2::ClearHistory */
};

static const MIDL_STUBLESS_PROXY_INFO IUrlHistoryStg2_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryStg2_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(10) _IUrlHistoryStg2ProxyVtbl =
{
    {
        &IUrlHistoryStg2_ProxyInfo,
        &IID_IUrlHistoryStg2,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        (void *)-1,  /* IUrlHistoryStg::AddUrl */
        (void *)-1,  /* IUrlHistoryStg::DeleteUrl */
        (void *)-1,  /* IUrlHistoryStg::QueryUrl */
        (void *)-1,  /* IUrlHistoryStg::BindToObject */
        (void *)-1,  /* IUrlHistoryStg::EnumUrls */
        (void *)-1,  /* IUrlHistoryStg2::AddUrlAndNotify */
        (void *)-1,  /* IUrlHistoryStg2::ClearHistory */
    }
};

static const MIDL_SERVER_INFO IUrlHistoryStg2_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryStg2_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const CInterfaceStubVtbl _IUrlHistoryStg2StubVtbl =
{
    {
        &IID_IUrlHistoryStg2,
        &IUrlHistoryStg2_ServerInfo,
        10,
        0
    },
    {
        CStdStubBuffer_METHODS
    }
};

static const unsigned short IUrlHistoryNotify_FormatStringOffsetTable[] =
{
    (unsigned short)-1,  /* IOleCommandTarget::QueryStatus */
    (unsigned short)-1,  /* IOleCommandTarget::Exec */
};

static const MIDL_STUBLESS_PROXY_INFO IUrlHistoryNotify_ProxyInfo =
{
    &Object_StubDesc,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryNotify_FormatStringOffsetTable[-3],
    0,
    0,
    0
};

static CINTERFACE_PROXY_VTABLE(5) _IUrlHistoryNotifyProxyVtbl =
{
    {
        &IUrlHistoryNotify_ProxyInfo,
        &IID_IUrlHistoryNotify,
    },
    {
        IUnknown_QueryInterface_Proxy,
        IUnknown_AddRef_Proxy,
        IUnknown_Release_Proxy,
        0,  /* IOleCommandTarget::QueryStatus */
        0,  /* IOleCommandTarget::Exec */
    }
};

static const MIDL_SERVER_INFO IUrlHistoryNotify_ServerInfo =
{
    &Object_StubDesc,
    0,
    __MIDL_ProcFormatString.Format,
    &IUrlHistoryNotify_FormatStringOffsetTable[-3],
    0,
    0,
    0,
    0
};

static const PRPC_STUB_FUNCTION IUrlHistoryNotify_table[] =
{
    STUB_FORWARDING_FUNCTION,
    STUB_FORWARDING_FUNCTION
};

static CInterfaceStubVtbl _IUrlHistoryNotifyStubVtbl =
{
    {
        &IID_IUrlHistoryNotify,
        &IUrlHistoryNotify_ServerInfo,
        5,
        &IUrlHistoryNotify_table[-3]
    },
    {
        CStdStubBuffer_DELEGATING_METHODS
    }
};

static const MIDL_STUB_DESC Object_StubDesc =
{
    0,
    NdrOleAllocate,
    NdrOleFree,
    {0}, 0, 0, 0, 0,
    __MIDL_TypeFormatString.Format,
    1, /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0,  /* notify & notify_flag routine table */
    1,  /* Flags */
    0,  /* Reserved3 */
    0,  /* Reserved4 */
    0   /* Reserved5 */
};

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this proxy.
#endif

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString =
{
    0,
    {
/* 0 (procedure IEnumSTATURL::Next) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x10),	/* server buffer = 16 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 26 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 32 (parameter rgelt) */
        NdrFcShort(0x11b),	/* flags: must size, must free, in, out, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x12),	/* type offset = 18 */
/* 38 (parameter pceltFetched) */
        NdrFcShort(0x158),	/* flags: in, out, base type, simple ref */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x09,	/* FC_ULONG */
        0x0,
/* 44 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 50 (procedure IEnumSTATURL::Skip) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 76 (parameter celt) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 82 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 88 (procedure IEnumSTATURL::Reset) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 114 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
/* 120 (procedure IEnumSTATURL::Clone) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 146 (parameter ppenum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x50),	/* type offset = 80 */
/* 152 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 158 (procedure IEnumSTATURL::SetFilter) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 184 (parameter poszFilter) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x56),	/* type offset = 86 */
/* 190 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 196 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 202 (procedure IUrlHistoryStg::AddUrl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x3),	/* method 3 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 228 (parameter pocsUrl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x5a),	/* type offset = 90 */
/* 234 (parameter pocsTitle) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x5c),	/* type offset = 92 */
/* 240 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 246 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 252 (procedure IUrlHistoryStg::DeleteUrl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x4),	/* method 4 */
        NdrFcShort(0x20),	/* stack size = 32 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x03,	/* 3 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 278 (parameter pocsUrl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x62),	/* type offset = 98 */
/* 284 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 290 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 296 (procedure IUrlHistoryStg::QueryUrl) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x5),	/* method 5 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x8),	/* client buffer = 8 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 322 (parameter pocsUrl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x66),	/* type offset = 102 */
/* 328 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 334 (parameter lpSTATURL) */
        NdrFcShort(0x1b),	/* flags: must size, must free, in, out */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x68),	/* type offset = 104 */
/* 340 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 346 (procedure IUrlHistoryStg::BindToObject) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x6),	/* method 6 */
        NdrFcShort(0x28),	/* stack size = 40 */
        NdrFcShort(0x14),	/* client buffer = 20 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x47,
        0x04,	/* 4 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 372 (parameter pocsUrl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0x6e),	/* type offset = 110 */
/* 378 (parameter riid) */
        NdrFcShort(0x10a),	/* flags: must free, in, simple ref */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0x76),	/* type offset = 118 */
/* 384 (parameter ppvOut) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x18),	/* stack offset = 24 */
        NdrFcShort(0x8e),	/* type offset = 142 */
/* 390 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 396 (procedure IUrlHistoryStg::EnumUrls) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x7),	/* method 7 */
        NdrFcShort(0x18),	/* stack size = 24 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x45,
        0x02,	/* 2 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 422 (parameter ppEnum) */
        NdrFcShort(0x13),	/* flags: must size, must free, out */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xa4),	/* type offset = 164 */
/* 428 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x10),	/* stack offset = 16 */
        0x08,	/* FC_LONG */
        0x0,
/* 434 (procedure IUrlHistoryStg2::AddUrlAndNotify) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x8),	/* method 8 */
        NdrFcShort(0x40),	/* stack size = 64 */
        NdrFcShort(0x10),	/* client buffer = 16 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x46,
        0x07,	/* 7 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 460 (parameter pocsUrl) */
        NdrFcShort(0x10b),	/* flags: must size, must free, in, simple ref */
        NdrFcShort(0x8),	/* stack offset = 8 */
        NdrFcShort(0xaa),	/* type offset = 170 */
/* 466 (parameter pocsTitle) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x10),	/* stack offset = 16 */
        NdrFcShort(0xac),	/* type offset = 172 */
/* 472 (parameter dwFlags) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x18),	/* stack offset = 24 */
        0x08,	/* FC_LONG */
        0x0,
/* 478 (parameter fWriteHistory) */
        NdrFcShort(0x48),	/* flags: in, base type */
        NdrFcShort(0x20),	/* stack offset = 32 */
        0x08,	/* FC_LONG */
        0x0,
/* 484 (parameter poctNotify) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x28),	/* stack offset = 40 */
        NdrFcShort(0xb0),	/* type offset = 176 */
/* 490 (parameter punkISFolder) */
        NdrFcShort(0xb),	/* flags: must size, must free, in */
        NdrFcShort(0x30),	/* stack offset = 48 */
        NdrFcShort(0xc2),	/* type offset = 194 */
/* 496 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x38),	/* stack offset = 56 */
        0x08,	/* FC_LONG */
        0x0,
/* 502 (procedure IUrlHistoryStg2::ClearHistory) */
        0x33,	/* FC_AUTO_HANDLE */
        0x6c,
        NdrFcLong(0x0),
        NdrFcShort(0x9),	/* method 9 */
        NdrFcShort(0x10),	/* stack size = 16 */
        NdrFcShort(0x0),	/* client buffer = 0 */
        NdrFcShort(0x8),	/* server buffer = 8 */
        0x44,
        0x01,	/* 1 params */
        0x0a,
        0x01,
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
        NdrFcShort(0x0),
/* 528 (return value) */
        NdrFcShort(0x70),	/* flags: out, return, base type */
        NdrFcShort(0x8),	/* stack offset = 8 */
        0x08,	/* FC_LONG */
        0x0,
        0x0
    }
};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString =
{
    0,
    {
        NdrFcShort(0x0),
/* 2 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  4 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 6 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/*  8 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 10 (FILETIME) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x8),	/* 8 */
        0x08,	/* FC_LONG */
        0x08,	/* FC_LONG */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 18 (struct _STATURL) */
        0x1a,	/* FC_BOGUS_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x38),	/* 56 */
        NdrFcShort(0x0),
        NdrFcShort(0x16),	/* Offset= 22 (46) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x36,	/* FC_POINTER */
        0x36,	/* FC_POINTER */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffea),	/* Offset= -22 (10) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe6),	/* Offset= -26 (10) */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xffe2),	/* Offset= -30 (10) */
        0x08,	/* FC_LONG */
        0x40,	/* FC_STRUCTPAD4 */
        0x5c,	/* FC_PAD */
        0x5b,	/* FC_END */
/* 46 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 48 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 50 (LPWSTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 52 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 54 (LPSTATURL) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xffda),	/* Offset= -38 (18) */
/* 58 (ULONG *) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
        0x09,	/* FC_ULONG */
        0x5c,	/* FC_PAD */
/* 62 (IEnumSTATURL *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x3c374a42),
        NdrFcShort(0xbae4),
        NdrFcShort(0x11cf),
        0xbf,
        0x7d,
        0x00,
        0xaa,
        0x00,
        0x69,
        0x46,
        0xee,

/* 80 (IEnumSTATURL **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (62) */
/* 84 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 86 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 88 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 90 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 92 (LPCOLESTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 94 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 96 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 98 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 100 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 102 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 104 (LPSTATURL) */
        0x12, 0x0,		/* FC_UP */
        NdrFcShort(0xffa8),	/* Offset= -88 (18) */
/* 108 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 110 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 112 (byte[8]) */
        0x1d,	/* FC_SMFARRAY */
        0x0,	/* 0 */
        NdrFcShort(0x8),	/* 8 */
        0x01,	/* FC_BYTE */
        0x5b,	/* FC_END */
/* 118 (IID) */
        0x15,	/* FC_STRUCT */
        0x3,	/* 3 */
        NdrFcShort(0x10),	/* 16 */
        0x08,	/* FC_LONG */
        0x06,	/* FC_SHORT */
        0x06,	/* FC_SHORT */
        0x4c,	/* FC_EMBEDDED_COMPLEX */
        0x0,
        NdrFcShort(0xfff1),	/* Offset= -15 (112) */
        0x5b,	/* FC_END */
/* 130 (REFIID) */
        0x11, 0x0,		/* FC_RP */
        NdrFcShort(0xfff2),	/* Offset= -14 (118) */
/* 134 (void *) */
        0x2f,  /* FC_IP */
        0x5c,  /* FC_PAD */
        0x2b,	/* Corr desc: parameter riid, FC_HYPER */
        0x0,	/* no operators */
        NdrFcShort(0x10),	/* offset = 16 */
        NdrFcShort(0x5),
/* 142 (void **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xfff6),	/* Offset= -10 (134) */
/* 146 (IEnumSTATURL *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x3c374a42),
        NdrFcShort(0xbae4),
        NdrFcShort(0x11cf),
        0xbf,
        0x7d,
        0x00,
        0xaa,
        0x00,
        0x69,
        0x46,
        0xee,

/* 164 (IEnumSTATURL **) */
        0x11, 0x10,		/* FC_RP [pointer_deref] */
        NdrFcShort(0xffec),	/* Offset= -20 (146) */
/* 168 (LPCOLESTR) */
        0x11, 0x8,	/* FC_RP [simple_pointer] */
/* 170 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 172 (LPCOLESTR) */
        0x12, 0x8,	/* FC_UP [simple_pointer] */
/* 174 */
        0x25,	/* FC_C_WSTRING */
        0x5c,	/* FC_PAD */
/* 176 (IOleCommandTarget *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0xb722bccb),
        NdrFcShort(0x4e68),
        NdrFcShort(0x101b),
        0xa2,
        0xbc,
        0x00,
        0xaa,
        0x00,
        0x40,
        0x47,
        0x70,

/* 194 (IUnknown *) */
        0x2f,	/* FC_IP */
        0x5a,	/* FC_CONSTANT_IID */
        NdrFcLong(0x00000000),
        NdrFcShort(0x0000),
        NdrFcShort(0x0000),
        0xc0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x46,

        0x0
    }
};

static const CInterfaceProxyVtbl* const _actxprxy_urlhist_ProxyVtblList[] =
{
    (const CInterfaceProxyVtbl*)&_IUrlHistoryStg2ProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IUrlHistoryStgProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IEnumSTATURLProxyVtbl,
    (const CInterfaceProxyVtbl*)&_IUrlHistoryNotifyProxyVtbl,
    0
};

static const CInterfaceStubVtbl* const _actxprxy_urlhist_StubVtblList[] =
{
    &_IUrlHistoryStg2StubVtbl,
    &_IUrlHistoryStgStubVtbl,
    &_IEnumSTATURLStubVtbl,
    &_IUrlHistoryNotifyStubVtbl,
    0
};

static PCInterfaceName const _actxprxy_urlhist_InterfaceNamesList[] =
{
    "IUrlHistoryStg2",
    "IUrlHistoryStg",
    "IEnumSTATURL",
    "IUrlHistoryNotify",
    0
};

static const IID * _actxprxy_urlhist_BaseIIDList[] =
{
    0,
    0,
    0,
    &IID_IOleCommandTarget,  /* IUrlHistoryNotify */
    0
};

static int __stdcall _actxprxy_urlhist_IID_Lookup(const IID* pIID, int* pIndex)
{
    int low = 0, high = 3;

    while (low <= high)
    {
        int pos = (low + high) / 2;
        int res = IID_GENERIC_CHECK_IID(_actxprxy_urlhist, pIID, pos);
        if (!res) { *pIndex = pos; return 1; }
        if (res > 0) low = pos + 1;
        else high = pos - 1;
    }
    return 0;
}

const ExtendedProxyFileInfo actxprxy_urlhist_ProxyFileInfo =
{
    (const PCInterfaceProxyVtblList*)_actxprxy_urlhist_ProxyVtblList,
    (const PCInterfaceStubVtblList*)_actxprxy_urlhist_StubVtblList,
    _actxprxy_urlhist_InterfaceNamesList,
    _actxprxy_urlhist_BaseIIDList,
    _actxprxy_urlhist_IID_Lookup,
    4,
    2,
    0,
    0,
    0,
    0
};
